name: Deploy Script Python

on:
  workflow_dispatch:
    inputs:
      example_input:
        description: 'Example input'
        required: false
        default: 'default_value'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute script Python
        run: |
          python main.py

      - name: Verify execution
        run: echo "Deploy do script Python concluído com sucesso!"

